version: 0.2

env:
  variables:
    PROJECT2: Site2
    PROJECT3: Site3
    DOTNET_FRAMEWORK: 4.5
phases:
  build:
    commands:
      - nuget restore
      - msbuild $env:PROJECT2.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Site2" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
      - cd $CODEBUILD_SRC_DIR_Site3
      - msbuild $env:PROJECT3.csproj /p:TargetFrameworkVersion=v$env:DOTNET_FRAMEWORK /p:Configuration=Release /p:DeployIisAppPath="Site3" /p:PackageAsSingleFile=false /p:OutDir=C:\codebuild\artifacts\ /t:Package
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\${env:PROJECT2}_Package\Archive\'
 
  secondary-artifacts:
    Site3:
        files:
          - '**/*'
        base-directory: $CODEBUILD_SRC_DIR_Site3
    
